### PR TITLE
89 invalid startup packet layout

### LINKED ISSUE #89: Uncaught error: Invalid startup packet layout: expected terminator as last byte
I catch connection error 
`Uncaught error: Invalid startup packet layout: expected terminator as last byte`

Looks like need to modify startup handshake

My solution was add one more empty string to startup:
```
 var bodyBuffer = writer.addCString('').addCString('').flush()
```

nodejs: v16.13.2
vertica: v10.0.0-0

### PR DESCRIPTION
**Pull request by DMickens**

### CODE REVIEW

File: packages/v-protocol/src/serializer.ts [hunk 1]
```diff
@@ -47,8 +47,7 @@ const startup = (opts: Record<string, string>): Buffer => {
     }
     writer.addCString(key).addCString(opts[key])
   }
-  writer.addCString('protocol_version').addInt32(parseInt(opts['protocol_version']))
-  writer.addCString('client_encoding').addCString('UTF8')
+  writer.addCString('protocol_version').addInt32(parseInt(opts['protocol_version'])).addCString('')
```
Comment (DMickens) [inline packages/v-protocol/src/serializer.ts:50]: client_encoding is not part of our protocol, leftover from postgres. 

null terminator from the client encoding was allowing the startup request packet to be accepted by 12.0 server

All tests pass locally now against 10.0 server as well, previously gave error for invalid startup packet.

Comment (blackeyepanda) [reply packages/v-protocol/src/serializer.ts:50]: probably add a comment for this null terminator hack?

**Review by blackeyepanda — APPROVED** [review]
Looks good to me
